### ISSUE TITLE
I3D pretrained model on WLASL

### ISSUE THREAD

**Issue by amna-ai** [dxli94/WLASL#47]
Is there a link to download the pretrained I3D model for WLASL? I am struggling with training it myself since I don't have a GPU.

**Comment by XiongTLu** [comment]
From the link published on Github you should be able to download the pre-training of the I3D model, I finished the download according to the official help file, but I have not trained it yet. If I experiment with the results I will reply to you via email with a new message.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxli94/WLASL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 下午3:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dxli94/WLASL] I3D pretrained model on WLASL (Issue #47)





 
Is there a link to download the pretrained I3D model for WLASL? I am struggling with training it myself since I don't have a GPU.

**Comment by amna-ai** [comment]
I downloaded the whole repo, I got it working but training the model made my laptop stuck. Apparently there's not enough RAM. 
I was thinking if I could download the pretrained weights on WLASL and just load them into the model.
Good Luck training !!
