### ISSUE TITLE
testing my own dataset

### ISSUE THREAD

**Issue by limkim65** [dxli94/WLASL#58]
Hi, I'm trying to make my own dataset and test.
I have few questions about it.

I am making new json file which replaces WLASL_v0_3.json(for preprocess of videos)
  Q1. My videos are not from youtube. Then should I decode with different fps?

 
I am making new json file which replaces nslt_100.json (which used in test_i3d.py)
  Q2. Do I have to make it manually?
  Q3. How do I know end_frame which is for action[2]? Should I calculate manually?

Other questions
  Q4. Does size(width, height) of video matters?
  Q5. Does length(time) of video matters?
  Q6. Any other critical things I need to consider making dataset?

I made those two json files and success to run the code, but the accuracy is extremely low, so I guess my json files are not appropriate or there's sth more I should consider.
I'm sorry if some questions are bit silly.  I would really appreciate it if you could reply. 

Thank you for your help.

**Comment by dxli94** [comment]
A1: more frames generally induces better recognition performance. Generally sampling at > 10 frames per second should be dense enough.
A2: yes.
A3: if each of your video contains only an isolated / "sign word", then end_frame can be just set as the total number of frames in that video snippet.
A4: To better reuse I3D features, it should keep the same as what I3D requires.
A5: word-level recognition videos are usually within a minute long. You may want to trim the video so that the gesture you want to recognize is clearly shown in the snippet.
A6: You need to better understand the data you are collecting. How many classes? How many instances per class? Are sample videos and annotations clean enough? These are critical for curating a new dataset.

Thanks.

**Comment by limkim65** [comment]
Thank you for replying right away. I would try to make my own dataset considering advise.
